/**
 * @fileoverview Annual events (歳時) themed DeckRecipes
 *
 * This module contains deck recipes based on annual events and seasonal celebrations.
 *
 * @module DeckRecipeSaiji
 */

import type { DeckRecipe } from '@/models/karuta';
import { ALL_PROTOTYPES } from './deck-recipe';
import { createKeywordFilter } from './filter-factory';

/**
 * Annual events themed deck recipes (歳時記)
 */
export const SAIJI_RECIPES: DeckRecipe[] = [
  {
    id: 'new-year',
    title: '🍊 お正月',
    apiParams: { ...ALL_PROTOTYPES },
    difficulty: 'intermediate',
    tags: ['歳時'],
    description: 'あけおめ',
    filter: createKeywordFilter([
      'NEW YEAR',
      '正月',
      'しょうがつ',
      'ショウガツ',
      '元日',
      '元旦',
      '新春',
      '初詣',
      'はつもうで',
      'ハツモウデ',
      '初日の出',
      'おせち',
      'オセチ',
      '年賀',
      '年玉',
      'としだま',
      'トシダマ',
      '凧',
      'たこ',
      'タコ',
      '羽根つき',
      'はねつき',
      'ハネツキ',
      'こま回し',
      'こままわし',
      'コマ回し',
      'コママワシ',
      '門松',
      '鏡餅',
      '福笑い',
      'ふくわらい',
      '神社',
      'じんじゃ',
      'ジンジャ',
      '🗻',
      '🦅',
      '🍆',
      '🌅',
      '🌄',
      '⛩️',
      '⛩',
      '🍊',
    ]),
  },
  {
    id: 'setsubun',
    title: '👹 節分',
    apiParams: { ...ALL_PROTOTYPES },
    difficulty: 'intermediate',
    tags: ['歳時'],
    description: '鬼は外 福は内',
    filter: createKeywordFilter([
      //
      'SETUBUN',
      '節分',
      '豆',
      'まめ',
      'マメ',
      '鬼',
      'おに',
      'オニ',
      '福',
      'ふく',
      'フク',
      '🍀',
      '🧧',
      '🧌',
      '👹',
      '😈',
    ]),
  },
  {
    id: 'valentines-day',
    title: '🍫 バレンタインデー',
    apiParams: { ...ALL_PROTOTYPES },
    difficulty: 'intermediate',
    tags: ['歳時'],
    description: 'チョコよりかるた',
    filter: createKeywordFilter([
      //
      'VALENTINE',
      'バレンタイン',
      'ばれんたいん',
      '🍫',
      '❤️',
      '💝',
      'ちょこ',
      'チョコ',
    ]),
  },
  {
    title: '🎋 七夕',
    id: 'tanabata',
    apiParams: { ...ALL_PROTOTYPES },
    difficulty: 'intermediate',
    tags: ['歳時'],
    description: '織姫と彦星の逢瀬',
    filter: createKeywordFilter([
      //
      'TANABATA',
      '七夕',
      'たなばた',
      'タナバタ',
      '棚ぼた',
      'たなぼた',
      'タナボタ',
      '短冊',
      'たんざく',
      'タンザク',
      '笹',
      'ささ',
      'ササ',
      '竹',
      'たけ',
      'タケ',
      '⭐',
      '🌠',
      '🎋',
    ]),
  },
  {
    id: 'respect-for-the-aged-day',
    title: '🪩 敬老の日',
    apiParams: { ...ALL_PROTOTYPES },
    difficulty: 'intermediate',
    tags: ['歳時'],
    description: '亀の甲より年の功',
    filter: createKeywordFilter([
      //
      'RESPECT FOR THE AGED DAY',
      '敬老',
      'けいろう',
      'ケイロウ',
      '年寄り',
      'としより',
      'トシヨリ',
      '老人',
      'ろうじん',
      'ロウジン',
      'シルバー',
      'しるばー',
      '爺',
      'じいさん',
      'じいちゃん',
      '婆',
      'ばあさん',
      'ばあちゃん',
      '👵🏼',
      '👴',
      '🧓🏻',
      '🐢',
    ]),
  },
  {
    id: 'halloween',
    title: '🎃 ハロウィン',
    apiParams: { ...ALL_PROTOTYPES },
    difficulty: 'intermediate',
    tags: ['歳時'],
    description: '🧙🧟👻💀',
    filter: createKeywordFilter([
      //
      'HALLOWEEN',
      'ハロウィン',
      'はろうぃん',
      '👻',
      '💀',
      '🎃',
      'おばけ',
      'オバケ',
      'ゴースト',
      '魔女',
      'かぼちゃ',
      'カボチャ',
      'パンプキン',
      'ゾンビ',
      'ぞんび',
      '🧟',
      '🧟‍♂️',
      '🧟‍♀️',
      '🧙',
      '🧙‍♀️',
    ]),
  },
  {
    title: '🎖️ ヒーローズ・リーグ',
    id: 'heroes-league',
    apiParams: { ...ALL_PROTOTYPES },
    difficulty: 'intermediate',
    tags: ['歳時'],
    description: '🦸‍♂️🦸‍♀️🦹‍♂️🦹‍♀️',
    filter: createKeywordFilter([
      //
      'HEROES LEAGUE',
      'HL',
      'ヒーロー',
      'ひーろー',
      '🦸',
      '🦸‍♀️',
      '🦸‍♂️',
      '🦹',
      '🦹‍♀️',
      '🦹‍♂️',
    ]),
  },
  {
    id: 'christmas',
    title: '🎄 クリスマス',
    apiParams: { ...ALL_PROTOTYPES },
    difficulty: 'intermediate',
    tags: ['歳時'],
    description: '🪅🎄🦌🛷🎅🎁',
    filter: createKeywordFilter([
      //
      'CHRISTMAS',
      'XMAS',
      "X'mas",
      'クリスマス',
      'くりすます',
      '🎁',
      '🎄',
      '🪅',
      '🎅',
      '🤶🏼',
      '🧑🏽‍🎄',
      '🦌',
      '🛷',
    ]),
  },
];
